# -*- coding: utf-8 -*-
"""Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e8U8zk46hkalnJ05PatjqsqZYC_8CK0k
"""

import pandas as pd

df= pd.read_csv('Salary.csv')

from google.colab import drive
drive.mount('/content/drive')

df.info()

if df.isnull().sum().sum() == 0:
    print("No null values found in the DataFrame. No replacement is needed.")
else:
    # Example of how you would replace nulls if they existed:
    # for column in df.columns:
    #     if df[column].isnull().any():
    #         if df[column].dtype == 'object': # Categorical
    #             mode_val = df[column].mode()[0]
    #             df[column].fillna(mode_val, inplace=True)
    #         else: # Numerical
    #             mean_val = df[column].mean()
    #             df[column].fillna(mean_val, inplace=True)
    print("Null values found. Placeholder for imputation code.")
    print(df.isnull().sum())





!pip install some_library

"""Replace `some_library` with the actual name of the library you want to install. If the library is already installed, `pip` will inform you. You can then import and use the library in subsequent cells."""

# Separate features (X) and target (y)
X = df[['YearsExperience']]
y = df['Salary']

print("Input variable (X) head:")
display(X.head())

print("\nOutput variable (y) head:")
display(y.head())

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

"""### 1. Linear Regression Model

First, we will train a simple Linear Regression model, which is a good starting point for understanding the relationship between our features and the target variable.
"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Initialize the Linear Regression model
linear_reg_model = LinearRegression()

# Train the model
linear_reg_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_lr = linear_reg_model.predict(X_test)

# Evaluate the model
mae_lr = mean_absolute_error(y_test, y_pred_lr)
mse_lr = mean_squared_error(y_test, y_pred_lr)
rmse_lr = np.sqrt(mse_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print(f"Linear Regression Model Performance:")
print(f"  Mean Absolute Error (MAE): {mae_lr:.2f}")
print(f"  Mean Squared Error (MSE): {mse_lr:.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_lr:.2f}")
print(f"  R-squared (R2): {r2_lr:.2f}")

"""### 2. Decision Tree Regressor

Next, let's train a Decision Tree Regressor, which can capture non-linear relationships in the data.
"""

from sklearn.tree import DecisionTreeRegressor

# Initialize the Decision Tree Regressor model
decision_tree_model = DecisionTreeRegressor(random_state=42)

# Train the model
decision_tree_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_dt = decision_tree_model.predict(X_test)

# Evaluate the model
mae_dt = mean_absolute_error(y_test, y_pred_dt)
mse_dt = mean_squared_error(y_test, y_pred_dt)
rmse_dt = np.sqrt(mse_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print(f"Decision Tree Regressor Model Performance:")
print(f"  Mean Absolute Error (MAE): {mae_dt:.2f}")
print(f"  Mean Squared Error (MSE): {mse_dt:.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_dt:.2f}")
print(f"  R-squared (R2): {r2_dt:.2f}")

"""### 3. Random Forest Regressor

Now, we'll use a Random Forest Regressor, an ensemble method that typically provides better accuracy than a single Decision Tree.
"""

from sklearn.ensemble import RandomForestRegressor

# Initialize the Random Forest Regressor model
random_forest_model = RandomForestRegressor(random_state=42)

# Train the model
random_forest_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_rf = random_forest_model.predict(X_test)

# Evaluate the model
mae_rf = mean_absolute_error(y_test, y_pred_rf)
mse_rf = mean_squared_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mse_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print(f"Random Forest Regressor Model Performance:")
print(f"  Mean Absolute Error (MAE): {mae_rf:.2f}")
print(f"  Mean Squared Error (MSE): {mse_rf:.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_rf:.2f}")
print(f"  R-squared (R2): {r2_rf:.2f}")

"""### 4. Support Vector Machine (SVM) Regressor

Let's try a Support Vector Machine (SVM) Regressor, which can be effective in high-dimensional spaces and for cases where the number of features is greater than the number of samples.
"""

from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# SVMs are sensitive to feature scaling, so we'll use a pipeline with StandardScaler
svm_model = Pipeline([
    ('scaler', StandardScaler()),
    ('regressor', SVR(kernel='rbf')) # Using a radial basis function kernel
])

# Train the model
svm_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_svm = svm_model.predict(X_test)

# Evaluate the model
mae_svm = mean_absolute_error(y_test, y_pred_svm)
mse_svm = mean_squared_error(y_test, y_pred_svm)
rmse_svm = np.sqrt(mse_svm)
r2_svm = r2_score(y_test, y_pred_svm)

print(f"Support Vector Machine (SVM) Regressor Model Performance:")
print(f"  Mean Absolute Error (MAE): {mae_svm:.2f}")
print(f"  Mean Squared Error (MSE): {mse_svm:.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_svm:.2f}")
print(f"  R-squared (R2): {r2_svm:.2f}")

"""### 5. K-Nearest Neighbors (KNN) Regressor

Finally, we'll implement a K-Nearest Neighbors (KNN) Regressor, a non-parametric method that makes predictions based on the 'k' closest training examples.
"""

from sklearn.neighbors import KNeighborsRegressor

# Initialize the K-Nearest Neighbors Regressor model
# You can experiment with different values of n_neighbors
knn_model = Pipeline([
    ('scaler', StandardScaler()), # KNN is also sensitive to feature scaling
    ('regressor', KNeighborsRegressor(n_neighbors=5)) # Using 5 neighbors
])

# Train the model
knn_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_knn = knn_model.predict(X_test)

# Evaluate the model
mae_knn = mean_absolute_error(y_test, y_pred_knn)
mse_knn = mean_squared_error(y_test, y_pred_knn)
rmse_knn = np.sqrt(mse_knn)
r2_knn = r2_score(y_test, y_pred_knn)

print(f"K-Nearest Neighbors (KNN) Regressor Model Performance:")
print(f"  Mean Absolute Error (MAE): {mae_knn:.2f}")
print(f"  Mean Squared Error (MSE): {mse_knn:.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_knn:.2f}")
print(f"  R-squared (R2): {r2_knn:.2f}")

"""### Consolidated Model Training and Evaluation using a Loop

To make the code more efficient and scalable, we can train and evaluate all models within a loop. This approach allows for easy comparison of performance metrics for various models.
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Define a list of models to train
models = [
    {
        'name': 'Linear Regression',
        'model': LinearRegression()
    },
    {
        'name': 'Decision Tree Regressor',
        'model': DecisionTreeRegressor(random_state=42)
    },
    {
        'name': 'Random Forest Regressor',
        'model': RandomForestRegressor(random_state=42)
    },
    {
        'name': 'Support Vector Machine (SVM) Regressor',
        'model': Pipeline([
            ('scaler', StandardScaler()),
            ('regressor', SVR(kernel='rbf'))
        ])
    },
    {
        'name': 'K-Nearest Neighbors (KNN) Regressor',
        'model': Pipeline([
            ('scaler', StandardScaler()),
            ('regressor', KNeighborsRegressor(n_neighbors=5))
        ])
    }
]

results = []

# Loop through each model, train, predict, and evaluate
for model_info in models:
    model_name = model_info['name']
    model = model_info['model']

    # Train the model
    model.fit(X_train, y_train)

    # Make predictions on the test set
    y_pred = model.predict(X_test)

    # Evaluate the model
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)

    results.append({
        'Model': model_name,
        'MAE': mae,
        'MSE': mse,
        'RMSE': rmse,
        'R2 Score': r2
    })

# Display the results in a DataFrame
results_df = pd.DataFrame(results)
results_df_sorted = results_df.sort_values(by='R2 Score', ascending=False)

print("\n--- Model Performance Comparison ---\n")
display(results_df_sorted)

"""### Visualizing Model Performance

To easily compare the performance of all trained models, let's create a bar chart of their R-squared (R2) scores.
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 7))
sns.barplot(x='Model', y='R2 Score', data=results_df_sorted, palette='viridis')
plt.xlabel('Model')
plt.ylabel('R-squared (R2) Score')
plt.title('Comparison of Model Performance (R2 Score)')
plt.xticks(rotation=45, ha='right')
plt.ylim(min(0, results_df_sorted['R2 Score'].min() - 0.1), 1) # Ensure y-axis starts appropriately
plt.tight_layout()
plt.show()

"""### Actual vs. Predicted Values for Random Forest Regressor

Let's visualize how well the Random Forest Regressor performed by plotting the actual salary values against its predicted values. A good model will have points clustering closely around the diagonal line, which represents perfect predictions.
"""

plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_test, y=y_pred_rf)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel('Actual Salary (y_test)')
plt.ylabel('Predicted Salary (y_pred_rf)')
plt.title('Random Forest Regressor: Actual vs. Predicted Salaries')
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Saving the Best Model

To save the best-performing model (Random Forest Regressor) for future use, we can use Python's `pickle` library. This will serialize the model object into a file.
"""

import pickle

# Define the filename for the saved model
model_filename = 'random_forest_regressor_model.pkl'

# Save the random_forest_model to the .pkl file
with open(model_filename, 'wb') as file:
    pickle.dump(random_forest_model, file)

print(f"Random Forest Regressor model successfully saved as '{model_filename}'")

"""### Loading the Saved Model (Optional)

If you want to load the model back into your environment in a new session, you can use the following code:
"""

# Example of how to load the model
# with open(model_filename, 'rb') as file:
#     loaded_model = pickle.load(file)

# print("Model loaded successfully!")
# # You can then use the loaded_model for predictions
# # y_pred_loaded = loaded_model.predict(X_test)